Heroku changing how buildpacks access environment variables during compile step

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -20,7 +20,16 @@
 mkdir -p ~/.ssh/
 chmod 700 ~/.ssh/
 
-echo "$SSH_KEY" > ~/.ssh/id_rsa
+env_dir=$3
+echo "env_dir=$env_dir"
+ssh_key_file="$env_dir/SSH_KEY"
+
+if [ ! -f "$ssh_key_file" ]; then
+    echo "$ssh_key_file not found";
+    exit 1;
+fi
+
+cat "$ssh_key_file" > ~/.ssh/id_rsa
 chmod 400 ~/.ssh/id_rsa
 
 echo 'StrictHostKeyChecking=no' > ~/.ssh/config
@@ -28,15 +37,14 @@ chmod 600 ~/.ssh/config
 
 mkdir -p "$1/.profile.d"
 cat > "$1/.profile.d/00-deploy-ssh-key.sh" << EOF
-echo 'deploy ssh deploy key'
+    echo 'deploy ssh deploy key'
 
-mkdir -p ~/.ssh/
-chmod 700 ~/.ssh/
+    mkdir -p ~/.ssh/
+    chmod 700 ~/.ssh/
 
-echo "$SSH_KEY" > ~/.ssh/id_rsa
-chmod 400 ~/.ssh/id_rsa
+    echo "$SSH_KEY" > ~/.ssh/id_rsa
+    chmod 400 ~/.ssh/id_rsa
 
-echo 'StrictHostKeyChecking=no' > ~/.ssh/config
-chmod 600 ~/.ssh/config
-
+    echo 'StrictHostKeyChecking=no' > ~/.ssh/config
+    chmod 600 ~/.ssh/config
 EOF
