Heroku hasn't started passing ENV_DIR yet

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -20,16 +20,18 @@
 mkdir -p ~/.ssh/
 chmod 700 ~/.ssh/
 
-env_dir=$3
-echo "env_dir=$env_dir"
-ssh_key_file="$env_dir/SSH_KEY"
-
-if [ ! -f "$ssh_key_file" ]; then
-    echo "$ssh_key_file not found";
-    exit 1;
+if [[ -z "$SSH_KEY" ]]; then
+    env_dir=$3
+    echo "env_dir=$env_dir"
+    ssh_key_file="$env_dir/SSH_KEY"
+    if [ ! -f "$ssh_key_file" ]; then
+        echo "$ssh_key_file not found";
+        exit 1;
+    fi
+    SSH_KEY = $(cat "$ssh_key_file")
 fi
 
-cat "$ssh_key_file" > ~/.ssh/id_rsa
+echo "$SSH_KEY" > ~/.ssh/id_rsa
 chmod 400 ~/.ssh/id_rsa
 
 echo 'StrictHostKeyChecking=no' > ~/.ssh/config
